# rule_generator.py
import time
import random

def generate_waf_rule(ip, attack_type, score):
    """
    Converts ML insights into industry-standard security rules.
    Satisfies Requirement 3.3 (Automated Mitigation).
    """
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    
    # 1. Generate a random Rule ID (looks more realistic than static 90001)
    rule_id = random.randint(90000, 99999)
    
    # 2. Determine Severity based on Risk Score
    severity = "CRITICAL" if score > 0.8 else "HIGH"
    
    # 3. Generate ModSecurity Rule (Enterprise Standard)
    # We use line continuations (\) for cleaner formatting
    modsec_rule = (
        f"# [Auto-Generated by ML-WAF] {timestamp}\n"
        f"SecRule REMOTE_ADDR \"@{ip}\" \\\n"
        f"    \"id:{rule_id},phase:1,deny,log,severity:{severity},\\\n"
        f"    msg:'Blocked due to {attack_type} (Score: {score:.2f})'\""
    )

    # 4. Generate IPTables Rule (Linux Kernel Level)
    # Using -I (Insert) ensures it goes to the TOP of the firewall chain
    iptables_rule = f"iptables -I INPUT -s {ip} -j DROP # Blocked: {attack_type}"

    # 5. Generate Nginx Rule (Web Server Level)
    nginx_rule = f"deny {ip}; # {attack_type}"

    return {
        "modsecurity": modsec_rule,
        "iptables": iptables_rule,
        "nginx": nginx_rule,
        "description": f"[{severity}] Anomaly from {ip} detected. Action: BLOCK."
    }